name: Build for Windows

on:
  push:

jobs:
  build-windows:
    name: Build for Windows
    runs-on: ubuntu-latest
            
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker Environment
        run: docker build -f Dockerfile -t builder .

      - name: Cache MinGW GCC
        id: cache-mingw-gcc
        uses: actions/cache@v3
        with:
          path: toolchain/mingw32
          key: ${{ runner.os }}-mingw-gcc

      - name: Build MinGW GCC
        if: steps.cache-mingw-gcc.outputs.cache-hit != 'true'
        run: docker run --user $(id -u):$(id -g) --rm -t -v $PWD:/build builder sh -c "cd /build && ./scripts/gcc-mingw.sh -arch=x86"

      - name: Get Source code
        run: docker run --user $(id -u):$(id -g) --rm -t -v $PWD:/build builder sh -c "cd /build && ./scripts/download_and_prepare.sh"

      - name: Build aMule (x86)
        run: docker run --user $(id -u):$(id -g) --rm -t -v $PWD:/build builder sh -c "cd /build && ./scripts/build-all.sh -arch=x86 -cc=gcc"

      - name: Build aMule (arm)
        run: |
          wget https://github.com/mstorsjo/llvm-mingw/releases/download/20240320/llvm-mingw-20240320-ucrt-ubuntu-20.04-x86_64.tar.xz
          tar xf llvm-mingw-*.tar.xz
          rm llvm-mingw-*.tar.xz
          mv llvm-mingw-* toolchain/clang
          docker run --user $(id -u):$(id -g) --rm -t -v $PWD:/build builder sh -c "cd /build && ./scripts/build-all.sh -arch=arm32 -cc=clang"

      - name: Prepare build artifacts
        run: |
          sha256sum *.7z
          mkdir -p upload
          cp amule*.7z upload

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: amule_windows
          path: upload

      - name: Batch release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./*.7z